server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: javauser
    password: 1234
  main:
    allow-circular-references: true


  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
    
  security:
    oauth2:
      client:
        registration:
         google:
          client-id: 488693894395-i0d0eimnk3qul96pihgcbr9adf0k5rne.apps.googleusercontent.com
          client-secret: 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
          scope:
          - email
          - profile
            
             

